# Generated by Django 5.1.7 on 2025-03-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_location', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_appointments', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSlots',
            fields=[
                ('slots_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('slot_9_10', models.IntegerField(default=0)),
                ('slot_10_11', models.IntegerField(default=0)),
                ('slot_11_12', models.IntegerField(default=0)),
                ('slot_12_1', models.IntegerField(default=0)),
                ('slot_1_2', models.IntegerField(default=0)),
                ('slot_2_3', models.IntegerField(default=0)),
                ('slot_3_4', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctors.doctor')),
            ],
        ),
    ]
